### ISSUE TITLE
Logo in homepage isn't responsive on mobile

### ISSUE THREAD

**Issue by DragomirDobrev** [jwillp/thegame-frontend#33]
The logo in homepage isn't resposive on mobile devices.

**Comment by jwillp** [comment]
I can confirm, see screenshot below:
![2017-09-21 14_27_16-the game _ home](https://user-images.githubusercontent.com/5913483/30712150-069b8eaa-9ed9-11e7-8433-9ec9f334f50d.png)

Could you take care of it ? I'll assign you.
